ticket/bar/urls.py
from django.urls import path, re_path
from bar import views

app_name="bar"

urlpatterns = [
    path('create/',views.create, name="create"),
    path('save/',views.save, name="save"),
]

ticket/member/urls.py
from django.urls import path, re_path
from member import views

app_name = 'member'

urlpatterns = [
    path( 'register/', views.member_register, name="register"),
    path( 'member_login', views.member_login, name="member_login")
]

ticket/ticket/urls.py
from django.contrib import admin
from django.urls import re_path,path,include
from member import views as member_views
from rest_framework import routers
from ticket import views
from rest_framework_jwt.views import refresh_jwt_token

router = routers.DefaultRouter(r'^api')
router.register(r':users',views.UserViewSet)
router.register(r':groups',views.GroupViewSet)
router.register(r':bar',views.BarViewSet)
router.register(r':member', views.MemberViewSet)

urlpatterns = [
    re_path(r'^$', member_views.index,name='index'),
    path('admin/', admin.site.urls),
    path('bar/', include('bar.urls')),
    path('member/', include('member.urls')),
    path('logout/', member_views.member_logout, name='logout'),
    re_path(r'^api', include(router.urls)),
    re_path(r'^rest-auth/', include('rest_auth.urls')),
    re_path(r'^rest-auth/registration/', include('rest_auth.registration.urls')),
    re_path(r'^auth/', include('rest_framework.urls')),
    re_path(r'^refresh-token/', refresh_jwt_token),
]

ticket/bar/models.py
from django.conf import settings
from django.db import models
from member.models import MemberProfile
# Create your models here.
class Bar(models.Model):
    Number = models.IntegerField()
    Summary = models.TextField(blank=False,default="Summary")
    Creator = models.ForeignKey(MemberProfile,on_delete=models.CASCADE)

    def __str__(self):
        return self.Summary

class BarThread(models.Model):
    Bar = models.OneToOneField(Bar,on_delete=models.CASCADE)
    Date = models.DateTimeField( auto_now=True )
    Text = models.TextField(blank=False)
    Creator = models.OneToOneField(MemberProfile,on_delete=models.CASCADE)

class BarContributer(models.Model):
    Bar = models.ForeignKey(Bar,on_delete=models.CASCADE)
    Member = models.ForeignKey(MemberProfile,on_delete=models.CASCADE)

ticket/member/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class MemberProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

ticket/bar/forms.py
from django import forms
from bar.models import Bar

class BarForm(forms.ModelForm):
    class Meta():
        model = Bar
        fields = ('Number','Summary')
        #fields = ('Number','Summary','Creator')

ticket/member/forms.py
from django import forms
from django.contrib.auth.models import User
from member.models import MemberProfile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class MemberForm(forms.ModelForm):
    class Meta():
        model = MemberProfile
        fields = ('picture',)

ticket/bar/views.py
from django.shortcuts import render
from bar.forms import BarForm
from bar.models import Bar
from member.models import MemberProfile

# Create your views here.
def create(request):
    edit_form = BarForm()
    return render(request, 'bar/edit.html',{'edit_form':edit_form})

def save(request):
    number = request.POST.get("Number")
    summary = request.POST.get("Summary")
    creator = MemberProfile.objects.filter(user=request.user)[0]

    bar_form = BarForm(data={'Number':number,'Summary':summary,'Creator':creator})

    if bar_form.is_valid():
        bar_form.save()

    return render(request, 'bar/edit.html',{'edit_form':bar_form})

ticket/member/views.py
from django.shortcuts import render
from member.forms import UserForm,MemberForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from bar.models import Bar
from member.models import MemberProfile

@login_required
def member_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def index(request):

    if request.user.is_authenticated:
        list = Bar.objects.filter(Creator=MemberProfile.objects.filter(user=request.user)[0])
        return render(request,'member/index.html',{'list':list})

    else:
        return member_login(request)

def member_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return render(request,'member/login.html')
        else:
            return render(request,'member/login.html')
    else:
        return render(request,'member/login.html')

def member_register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = MemberForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:

            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = MemberForm()

    return render(request, 'member/registration.html',
                            {   'user_form': user_form,
                                'profile_form' : profile_form,
                                'registered' : registered })

ticket/templates/bar/edit.html
{% extends "ticket/base.html" %}
{% block body_block %}

<div class="jumbotron">

  <form action="/api:bar/" method="post" enctype="multipart/form-data">
      {% csrf_token %}
    {{ edit_form.as_p }}

    <input type="submit" name="" value="Save">
  </form>

</div>

{% endblock %}

ticket/templates/member/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top navbar-inverse">
      <a class="navbar-brand" href="{% url 'index' %}">Ticket System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'bar:create' %}">New Ticket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

ticket/templates/member/index.html
{% extends "member/base.html" %}
{% block body_block %}

  <h1>Ticket Members</h1>

  {% if list %}

    <h4>User Has Tickets</h4>
    {% for obj in list %}

    <tr>
      <td>{{ obj.Number }}</td>
      <td>{{ obj.Summary }}</td>
    </tr>

    {% endfor %}

  {% endif %}

{% endblock %}

ticket/templates/member/login.html
{% extends "member/base.html" %}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form action="{% url 'member:member_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" value="" placeholder="Enter you username">
      <label for="password">Password:</label>
      <input type="password" name="password" value="">
      <input type="submit" name="" value="Login">
    </form>
    <a href="{% url 'member:register' %}">Register New User</a>
</div>

{% endblock %}

ticket/templates/member/registration.html
{% extends "member/base.html" %}
{% block body_block %}

<div class="jumbotron">

  {% if registered %}
    <h1>Thank You for Registering</h1>
  {% else %}
    <h1>Register Here!</h1>
    <h3>Fill out the form:</h3>

    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}

      <input type="submit" name="" value="Register">
    </form>

  {% endif %}

</div>

{% endblock %}

ticket/templates/ticket/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top navbar-inverse">
      <a class="navbar-brand" href="{% url 'index' %}">Ticket System</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'bar:create' %}">New Ticket</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>